name: "Create New Sheet"

# Creates a new sheet at the beginning of the week

on: push

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        # access_token_lifetime: '300s'
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Show Token'
      run: |
        ls
        cat *.json


