name: "Run Gym Scripts"

# Creates a new sheet at the beginning of the week

on: 
  workflow_dispatch: {}
  schedule:
    # Create sheet weekly on Monday at 2:00AM
    - cron: '0 2 * * 1'
    # Update sheet weekly on Saturday at 2:00AM
    - cron: '0 2 * * 6'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        access_token_lifetime: '300s'
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Create New Sheet
      if: github.event.schedule == '0 2 * * 1'
      run: python createNewSheetForActions.py

    - name: Update Sheet
      if: github.event.schedule == '0 2 * * 6'
      run: python updateSheetForActions.py


